feature/endpoint-login
carlosrizon/orion-bootcamp pull request #1
Opened 2023-10-23 00:17 UTC by itzinn

Endpoint de login foi criado no arquivo "routes.ts", e utiliza o controller "AuthController.ts" para processar as requisições feitas ao endpoint.

Para fins de teste, criei o seguinte usuário em um banco de dados fictício:
teste@teste.com
teste123

2023-10-23 00:28 UTC, itzinn commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Pablo Montemor] [MarvelPedia - Beta Orions] Criação do Endpoint de Login](https://trello.com/c/mSv98VkA/290-pablo-montemor-marvelpedia-beta-orions-cria%C3%A7%C3%A3o-do-endpoint-de-login)

2023-10-24 01:51 UTC, carlosrizon approved these changes
Pode resolver essas questões simples e dar merge

2023-10-24 01:51 UTC, carlosrizon commented on docker-compose.yml
> +      # DB_CONNECTION_STRING: mongodb://orion_root:j5m966qp7jiypfda@orion-mongo:27017
Pode remover o que não está sendo utilizado

2023-10-24 01:51 UTC, carlosrizon commented on package.json
> +    "bcrypt": "^5.1.1",
Fixa as versões para não ter perigo de quebrar

2023-10-24 01:56 UTC, carlosrizon requested changes

2023-10-24 01:56 UTC, carlosrizon commented on src/controller/AuthController.ts
> +          .send({ date: new Date(), status: true, data: 'Senha inválida.' });
aqui o status e "false"

2023-10-24 02:59 UTC, itzinn commented
valeu!

2023-10-24 02:59 UTC, merged