feature/entidade-personagem
carlosrizon/orion-bootcamp pull request #12
Opened 2023-11-04 00:06 UTC by itzinn

Criei a entidade Character no banco e fiz uma migration que insere alguns exemplos.

2023-11-05 19:08 UTC, itzinn commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Pablo Montenor] Criar entidade Personagem](https://trello.com/c/nhUwjrN2/474-pablo-montenor-criar-entidade-personagem)

2023-11-07 02:05 UTC, carlosrizon requested changes

2023-11-07 02:05 UTC, carlosrizon commented on package.json
> +    "typeorm": "^0.3.17"
fixar a versão

2023-11-07 15:35 UTC, itzinn commented
Fiz as correções e algumas melhorias adicionais

2023-11-08 02:51 UTC, carlosrizon approved these changes

2023-11-08 02:51 UTC, merged