feature/contabilizacao-de-metrica
carlosrizon/orion-bootcamp pull request #13
Opened 2023-11-05 22:06 UTC by itzinn

Criei uma entidade para guardar a métrica de cliques por personagem por usuário.
Também fiz um CharacterController que possui um método countClick para contabilizar essa métrica, recebendo o id do usuário que efetuou o clique e o id do personagem do card clicado.

Para efetuar a contabilização, uma requisição get deve ser feita ao endpoint /v1/select/:character_id, com o id do personagem do card clicado. O id do usuário será obtido pelo token JWT.

2023-11-05 22:09 UTC, itzinn commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Pablo Montemor] Contabilizar métrica de clique por usuário por personagem](https://trello.com/c/8ouBObJy/480-pablo-montemor-contabilizar-m%C3%A9trica-de-clique-por-usu%C3%A1rio-por-personagem)

2023-11-07 02:10 UTC, carlosrizon requested changes

2023-11-07 02:10 UTC, carlosrizon commented on src/controller/CharacterController.ts
> +  async countClick(req: Request, res: Response) {
Faltou a documentação do swagger

2023-11-08 02:52 UTC, carlosrizon approved these changes

2023-11-08 02:52 UTC, merged