refactor(mail): replica alteração de coluna name de entidade usuario
carlosrizon/orion-bootcamp pull request #15
Opened 2023-11-06 03:56 UTC by ewelyn-samaris

Esse PR implementa mudanças para melhorias no processo de cadastro de usuários. São elas:

- Divide coluna name em firstName e lastName, conforme história;
- Replica alteração da coluna name em arquivos ainda desatualizados;
- Implementa validação de idade mínima para acesso à plataforma, conforme história;
- Retira critério de letra maiúscula para senha, conforme história;
- Fixa mensagem de retorno para status code 500, padronizando mensagens em portuuês;
- Ajusta retorno da validação de duplicidade de e-mail no userValidator, incluindo-o no status code 400;

```
//Antes:
// não retornava erro no userValidator, sendo retornado posteriormente pelo banco
 .custom(async (email: string) => {
      const repository = new Repository();
      const existingUser = await repository.findOneByEmail(email);
      if (existingUser) {
        return false;
      }
    })
    .withMessage('E-mail já cadastrado'), 

//Depois:
.custom(async (email: string) => {
      const repository = new Repository();
      const existingUser = await repository.findOneByEmail(email);
      if (existingUser) {
        return Promise.reject('E-mail já cadastrado');
      }
      return Promise.resolve();
    }),
```
- Atualiza exemplo do swagger;
- Inclui scripts de show e revert migrations no package.json.

2023-11-07 02:24 UTC, carlosrizon requested changes

2023-11-07 02:24 UTC, carlosrizon commented on src/middleware/TranslateMiddleware.ts
> +export default class TranslateMiddleware {
Mesma coisa aqui, ele não precisa ser um middleware

2023-11-09 02:21 UTC, carlosrizon requested changes

2023-11-09 02:21 UTC, carlosrizon commented on docker-compose.yml
> -      JWT_SECRET_KEY: 3RWS8GmVfz6Ax7l0q5nQ2RUySvPsdh0aK3GSY4mTRhlICvi8Il
Porque está sendo removido ?

2023-11-09 02:21 UTC, carlosrizon commented on src/handlers/CharactersHandler.ts
> +      //res.json(response.data);
porque ta comentado ?

2023-11-09 02:21 UTC, carlosrizon commented on src/utils/marvelGetHelpers.ts
> +  return 'https://gateway.marvel.com/v1/public';
Usar env aqui

2023-11-09 02:50 UTC, ewelyn-samaris commented on docker-compose.yml
> -      JWT_SECRET_KEY: 3RWS8GmVfz6Ax7l0q5nQ2RUySvPsdh0aK3GSY4mTRhlICvi8Il
Foi colocado no .env

2023-11-09 02:50 UTC, ewelyn-samaris commented on src/handlers/CharactersHandler.ts
> +      //res.json(response.data);
explica o porque da repetição do 'data'

2023-11-09 03:00 UTC, ewelyn-samaris commented on src/utils/marvelGetHelpers.ts
> +  return 'https://gateway.marvel.com/v1/public';
Colocado

2023-11-09 03:18 UTC, ewelyn-samaris commented on src/middleware/TranslateMiddleware.ts
> +export default class TranslateMiddleware {
Foi retirado

2023-11-09 05:36 UTC, ewelyn-samaris commented on src/handlers/CharactersHandler.ts
> +      //res.json(response.data);
Retirado

2023-11-10 01:42 UTC, carlosrizon requested changes

2023-11-10 01:42 UTC, carlosrizon commented on docker-compose.yml
> -      JWT_SECRET_KEY: 3RWS8GmVfz6Ax7l0q5nQ2RUySvPsdh0aK3GSY4mTRhlICvi8Il
JWT_SECRET_KEY: ${JWT_SECRET_KEY}

Sim, mas você pode atribuir o valor da env para a enviroment do container, além disso como a aplicação dentro do container tem acesso ao arquivo .env se ela não está dentro do container ?

2023-11-10 01:42 UTC, carlosrizon commented on src/repository/CharacterRepository.ts
> +      const characterRegistered = await this.findOneByMarvelId(
A lógica consome muitos recursos de processamento, pois, para cada registro, você precisa consultar o banco de dados para verificar se ele já existe e, somente após a verificação, você insere ou atualiza o registro.

Uma abordagem mais eficiente é fazer um único comando de inserção no banco de dados para atualizar registros existentes ou criar novos registros.

const characters = [
  { name: 'Homem Aranha' }, // Cria
  { id: 2, name: 'Hulk' } // Atualiza
];
const repository = getRepository(Character);
await repository.save(characters);

2023-11-10 20:41 UTC, closed without merging