feature/endpoint-get-characters
carlosrizon/orion-bootcamp pull request #16
Opened 2023-11-07 21:49 UTC by itzinn

Reformulei o endpoint getCharacters para obter as informações diretamente do banco de dados. Ele retorna paginas de personagens de acordo com o número de página especificado.

Também adicionei o middleware de autenticação à rota do endpoint.

2023-11-07 21:51 UTC, itzinn commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Pablo Montemor] Criar endpoint que retorna páginas de personagens traduzidas](https://trello.com/c/tFf1oVB6/450-pablo-montemor-criar-endpoint-que-retorna-p%C3%A1ginas-de-personagens-traduzidas)

2023-11-08 02:55 UTC, carlosrizon requested changes

2023-11-08 02:55 UTC, carlosrizon commented on src/controller/CharacterController.ts
> +  async getCharactersPage(req: Request, res: Response) {
Documentação do swagger

2023-11-08 02:55 UTC, carlosrizon commented
Resolver os conflitos

2023-11-08 12:03 UTC, itzinn commented
Fiz as alterações, valeu!

2023-11-08 12:04 UTC, merged