Feature/disparo email cadastro
carlosrizon/orion-bootcamp pull request #2
Opened 2023-10-24 00:12 UTC by NickolasLuan

Criei uma pasta biblioteca com o arquivo mail.ts que contém uma classe para disparar os e-mails de cadastro.

2023-10-24 01:48 UTC, carlosrizon commented
Resolve os conflitos na branch

2023-10-24 01:55 UTC, carlosrizon requested changes

2023-10-24 01:55 UTC, carlosrizon commented on docker-compose.yml
> +      # DB_CONNECTION_STRING: mongodb://orion_root:j5m966qp7jiypfda@orion-mongo:27017
Pode remover o que não está sendo utilizado

2023-10-24 01:55 UTC, carlosrizon commented on package.json
> +  "devDependencies": {
Fixa todas as versões, isso impede que quebre em alguma atualização

2023-10-24 04:24 UTC, NickolasLuan commented on docker-compose.yml
> +      # DB_CONNECTION_STRING: mongodb://orion_root:j5m966qp7jiypfda@orion-mongo:27017
Certo

2023-10-24 04:53 UTC, NickolasLuan commented on package.json
> +  "devDependencies": {
Fixado.

2023-10-24 05:02 UTC, NickolasLuan commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Nickolas Luan] [MarvelPedia - Beta Orions] Disparo de e-mail de confirmação de cadastro](https://trello.com/c/5YuZTpwi/283-nickolas-luan-marvelpedia-beta-orions-disparo-de-e-mail-de-confirma%C3%A7%C3%A3o-de-cadastro)

2023-10-25 01:52 UTC, carlosrizon approved these changes

2023-10-25 01:52 UTC, merged