refactor(userController): retorna usuário diretamente após salvar
carlosrizon/orion-bootcamp pull request #35
Opened 2023-11-17 01:33 UTC by ewelyn-samaris

Esse PR implementa as alterações:
- Adiciona decorators apropriados para colunas createdAt e lastUpdate que permite atualização automática de dados ao salvar;
- Retorna usuário diretamente após salvar em banco de dados sem retornar a hash;
- Remove necessidade de busca por usuário no controller.

2023-11-17 02:23 UTC, carlosrizon requested changes

2023-11-17 02:23 UTC, carlosrizon commented on src/repository/UserRepository.ts
> +    return this.findOneByEmail(newUser.email);
não precisa fazer uma nova consulta, e so usar del newUser.password para deletar o atributo do hash.

2023-11-17 03:19 UTC, ewelyn-samaris commented on src/repository/UserRepository.ts
> +    return this.findOneByEmail(newUser.email);
Implementado

2023-11-18 02:17 UTC, carlosrizon requested changes

2023-11-18 02:17 UTC, carlosrizon commented on src/repository/UserRepository.ts
> +  private _userCopyWithoutHashPassword(newUser: User){
Adiciona essa logica dentro do controller

2023-11-22 18:39 UTC, closed without merging