Endpoint de recuperação de senha
carlosrizon/orion-bootcamp pull request #39
Opened 2023-11-18 23:31 UTC by NickolasLuan

- Adiciona entidade Token para armazenar os tokens do usuário.
- Adiciona controller responsável pelo processo de recuperação de senha
- Adiciona endpoint responsável por validar o email do usuário antes de enviar o email de recuperação de senha.
- Adiciona endpoint responsável por mudar a senha do usuário, salvar o token no banco de dados e garantir que o usuário mude a senha apenas uma vez por Token gerado.

2023-11-22 11:10 UTC, carlosrizon requested changes

2023-11-22 11:10 UTC, carlosrizon commented on src/controller/RecoveryController.ts
> +      console.log('E-mail recebido:', userEmail);
E interresante ter esses loggers no banco, não e uma boa pratica encher o codigo de console.log

2023-11-22 11:10 UTC, carlosrizon commented on src/library/mail.ts
> +        <h3><p><a href="http://localhost:4444/v1/changepassword?token=${token}">Recuperar senha</a></p></h3><br>
Aqui não seria uma url do front-end ? porque a rota 4444/v1/changepassword o front end que precisa chamar.

2023-11-22 20:42 UTC, NickolasLuan commented on src/controller/RecoveryController.ts
> +      console.log('E-mail recebido:', userEmail);
Coloquei pra testes mesmo, vou remover

2023-11-22 20:42 UTC, NickolasLuan commented on src/library/mail.ts
> +        <h3><p><a href="http://localhost:4444/v1/changepassword?token=${token}">Recuperar senha</a></p></h3><br>
Vou alterar, valeu!

2023-11-22 22:29 UTC, NickolasLuan commented on src/library/mail.ts
> +        <h3><p><a href="http://localhost:4444/v1/changepassword?token=${token}">Recuperar senha</a></p></h3><br>
Alterado

2023-11-22 22:45 UTC, NickolasLuan commented on src/controller/RecoveryController.ts
> +      console.log('E-mail recebido:', userEmail);
Tudo certo

2023-11-23 01:53 UTC, carlosrizon approved these changes

2023-11-23 01:53 UTC, carlosrizon commented on src/library/mail.ts
> +        <h3><p><a href="http://localhost:4200/change-password?token=${token}">Recuperar senha</a></p></h3><br>
Aqui você vai precisar colocar envs dps, para fazer a integração com o front e necessario, porque o front não ta no localhost

2023-11-23 01:55 UTC, merged