REFAZ PR PARA Feature/survey endpoint get
carlosrizon/orion-bootcamp pull request #46
Opened 2023-11-23 09:23 UTC by ewelyn-samaris

Como havia explicado, acidentalmente desfiz as alterações que essa branch implementava. 
No próprio Github, na relação de branchs ativas, abri novo PR para a branch.

2023-11-23 16:43 UTC, carlosrizon requested changes

2023-11-23 16:43 UTC, carlosrizon commented on src/controller/SurveyController.ts
> +      .json({ date: new Date(), status: true, data: { eligible: true } });
porque ta chumbado ? vai adicionar a logica depois ?

2023-11-23 20:28 UTC, ewelyn-samaris commented on src/controller/SurveyController.ts
> +      .json({ date: new Date(), status: true, data: { eligible: true } });
O tratamento dos casos não elegíveis é feito no validator. Só segue para o controller quando finalizadas todas as validações.

2023-11-24 02:11 UTC, carlosrizon approved these changes

2023-11-24 02:13 UTC, carlosrizon approved these changes

2023-11-24 02:13 UTC, merged