Correção da validação de recuperação de senha
carlosrizon/orion-bootcamp pull request #51
Opened 2023-11-26 18:53 UTC by NickolasLuan

- Mudança da validação da recuperação de senha (Permite mudar a senha sem a obrigatoriedade de uma letra maiúscula.)
- Mudança do status quando o e-mail do usuário não é encontrado. (Melhora a segurança da aplicação para evitar ataques de força bruta)
-Adaptação do dockerfile para o deploy da AWS.

OBS: A mudança da validação de recuperação de senha foi conversada com a luiza e foi decidido a mesma validação da tela de cadastro para a tela de recuperação de senha (Pelo menos 8 caracteres, 1 letra, 1 número, 1 caractere especial).

2023-11-29 02:18 UTC, carlosrizon requested changes

2023-11-29 02:18 UTC, carlosrizon commented on src/library/mail.ts
> +        <h3><p><a href="https://marvelpedia-orionis-front.vercel.app/change-password?token=${token}">Recuperar senha</a></p></h3><br>
Aqui precisa ser uma env...

2023-11-29 02:18 UTC, carlosrizon commented on Dockerfile
> +COPY . .
Essa alteração foi proposital ?

2023-11-29 12:22 UTC, NickolasLuan commented on src/library/mail.ts
> +        <h3><p><a href="https://marvelpedia-orionis-front.vercel.app/change-password?token=${token}">Recuperar senha</a></p></h3><br>
Blza, já corrigi

2023-11-30 02:34 UTC, carlosrizon approved these changes

2023-11-30 02:34 UTC, merged