feat: add validação de tamanho de comentário, corrige documentação, altera responses #Survey
carlosrizon/orion-bootcamp pull request #61
Opened 2023-12-02 21:22 UTC by ewelyn-samaris

Esse PR implementa:

* Adiciona indicação de necessidade de autenticação do usuário na documnetação Swagger do SurveyController;
* Remove verificação de elegibilidade de usuário para pesquisa do validator (uma vez que não há parâmetros a serem validaos) e os coloca no controller;
* Customiza retornbo de inegibilidade à pesquisa com status 200 para get (se elegível ou não) e 403 para POST, se inelegível;
* Adiciona validação de tamanho do texto de comentário, se dentro do limite máximo definido.

2023-12-03 23:34 UTC, carlosrizon requested changes

2023-12-03 23:34 UTC, carlosrizon commented on src/controller/SurveyController.ts
> +   *       '403':
O status 403 deve ser utilizado quando um usuario que autenticado acessa uma rota que ele não tem permissão, o que não e nesse caso.

2023-12-05 01:09 UTC, ewelyn-samaris commented on src/controller/SurveyController.ts
> +   *       '403':
Corrigido

2023-12-05 02:28 UTC, carlosrizon approved these changes

2023-12-05 02:28 UTC, merged