feat: Endpoint post de comentários
carlosrizon/orion-bootcamp pull request #63
Opened 2023-12-02 23:44 UTC by NickolasLuan

- Criação da entidade de comentários.
- Criação do endpoint post para criar comentário do usuário.

2023-12-03 00:32 UTC, NickolasLuan commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Nickolas Luan] Criar entidade de comentários](https://trello.com/c/jTpRtJHj/788-nickolas-luan-criar-entidade-de-coment%C3%A1rios)

2023-12-03 00:33 UTC, NickolasLuan commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Nickolas Luan] Criar endpoint POST de comentários](https://trello.com/c/xFQSeaBF/789-nickolas-luan-criar-endpoint-post-de-coment%C3%A1rios)

2023-12-03 23:38 UTC, carlosrizon requested changes

2023-12-03 23:38 UTC, carlosrizon commented on src/controller/CommentController.ts
> +      const user = await userRepository.findOne({ where: { id: user_id } });
Esse user_id não e do usuario autenticado ?.... em qual cenario ele pode não existir ?

2023-12-03 23:38 UTC, carlosrizon commented on src/entity/Comments.ts
> +  @CreateDateColumn()
padroniza em camelCase

2023-12-04 00:05 UTC, NickolasLuan commented on src/controller/CommentController.ts
> +      const user = await userRepository.findOne({ where: { id: user_id } });
Eu implementei essa validação mais pra ter certeza que o id inserido é de um usuário real

2023-12-04 00:07 UTC, NickolasLuan commented on src/controller/CommentController.ts
> +      const user = await userRepository.findOne({ where: { id: user_id } });
Acha que é necessário a validação?

2023-12-05 02:32 UTC, carlosrizon approved these changes

2023-12-05 03:12 UTC, merged