Feature/entidade usuario endpoint cadastro
carlosrizon/orion-bootcamp pull request #7
Opened 2023-10-28 03:43 UTC by ewelyn-samaris

Adiciona entidade de usuário, middleware de validação de dados e endpoint de cadastro.

2023-10-28 04:22 UTC, ewelyn-samaris commented
Conflitos resolvidos.

2023-10-28 12:50 UTC, carlosrizon requested changes

2023-10-28 12:50 UTC, carlosrizon commented on package.json
> +    "@types/cors": "^2.8.14",
Os pacotes devem estar fixados

2023-10-28 12:50 UTC, carlosrizon commented on src/controller/UserController.ts
> +   * @swagger
Hello pode remover

2023-10-28 12:50 UTC, carlosrizon commented on src/controller/UserController.ts
> +   *           schema:
você precisa adicionar um campo chamado example.. https://swagger.io/docs/specification/adding-examples/

2023-10-28 21:40 UTC, ewelyn-samaris commented
Fiz as correções solicitadas e tratei os conflitos.

2023-10-28 21:48 UTC, ewelyn-samaris commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Ewelyn Sâmaris] Endpoint de Cadastro de Usuário](https://trello.com/c/VQYydnTq/282-ewelyn-s%C3%A2maris-endpoint-de-cadastro-de-usu%C3%A1rio)

2023-10-28 21:48 UTC, ewelyn-samaris commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Ewelyn Sâmaris] Entidade de Usuário (Flag Confirmação)](https://trello.com/c/HOzuAyYz/281-ewelyn-s%C3%A2maris-entidade-de-usu%C3%A1rio-flag-confirma%C3%A7%C3%A3o)

2023-10-30 11:10 UTC, carlosrizon requested changes

2023-10-30 11:10 UTC, carlosrizon commented on src/routes.ts
>  router.post('/login', new AuthController().login);
aproveita para padrinizar aqui com /v1

2023-10-31 00:07 UTC, ewelyn-samaris commented on src/routes.ts
>  router.post('/login', new AuthController().login);
Atualizado

2023-10-31 01:49 UTC, carlosrizon approved these changes

2023-10-31 01:50 UTC, merged