Feature/mudanca mensagem email
carlosrizon/orion-bootcamp pull request #8
Opened 2023-10-31 07:39 UTC by NickolasLuan

Realizei algumas mudanças no código. Apliquei uma validação para caso o usuário já confirmou o email e ele clique denovo no link de confirmação, mostre uma mensagem de email já confirmado. Na classe de criação de usuário do endpoint de cadastro, chamei a classe com o método para envio de email. Também realizei algumas modificações no layout do corpo do email conforme a história do projeto.

2023-11-01 02:16 UTC, carlosrizon requested changes

2023-11-01 02:16 UTC, carlosrizon commented on package.json
> +    "express-validator": "^7.0.1",
fixa a versão

2023-11-01 03:29 UTC, NickolasLuan commented on package.json
> +    "express-validator": "^7.0.1",
Fixado.

2023-11-02 01:51 UTC, carlosrizon requested changes

2023-11-02 01:51 UTC, carlosrizon commented on package.json
> +    "express-validator": "^7.0.1",
aqui ainda ta aparecendo lib sem fixação

2023-11-02 01:51 UTC, carlosrizon approved these changes

2023-11-02 03:05 UTC, NickolasLuan commented on package.json
> +    "express-validator": "^7.0.1",
Fixei, vou fazer o merge

2023-11-02 03:21 UTC, merged