feature/adiciona-middleware-dashboard
carlosrizon/orion-bootcamp pull request #9
Opened 2023-11-01 00:37 UTC by itzinn

Implementei no arquivo routes o middleware de autenticação no endpoint dashboard.

2023-11-01 00:39 UTC, itzinn commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Pablo Montenor] Adicionar middleware de autenticação para dashboard](https://trello.com/c/0IQiIlYD/449-pablo-montenor-adicionar-middleware-de-autentica%C3%A7%C3%A3o-para-dashboard)

2023-11-01 02:14 UTC, carlosrizon requested changes

2023-11-01 02:14 UTC, carlosrizon commented on package.json
> +    "bcrypt": "^5.1.1",
fixa as versões

2023-11-01 02:14 UTC, carlosrizon commented on src/routes.ts
> +router.all('/dashboard', authenticateToken, (req, res) => {
Mantenha o padrão de api com um prefixo /v1

2023-11-02 01:52 UTC, carlosrizon approved these changes

2023-11-02 01:52 UTC, merged